/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Shardul
 */
public class PamHome extends javax.swing.JFrame {

    /**
     * Creates new form PamHome
     */
    public PamHome() {
        initComponents();
    }
    public PamHome(String para){
        initComponents();
        jLabel2.setText(para);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1045, 836));
        setMinimumSize(new java.awt.Dimension(1045, 836));
        setPreferredSize(new java.awt.Dimension(1045, 836));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setPreferredSize(new java.awt.Dimension(6, 20));
        getContentPane().add(jLabel45);
        jLabel45.setBounds(534, 526, 177, 29);

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setText("Enter the name of the poacher:");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(301, 326, 206, 45);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Generate Fine");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(416, 438, 171, 47);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField14);
        jTextField14.setBounds(560, 216, 177, 30);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(560, 335, 177, 31);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel44.setText("Enter the ID of the animal which was poached:");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(201, 207, 306, 45);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Your ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(282, 145, 109, 36);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(434, 145, 137, 36);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Project\\UI\\Spy_64px.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 40, 60, 56);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Protected Area Manager");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(434, 53, 280, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Fine Amount:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(375, 526, 114, 25);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Logout !");
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel49MousePressed(evt);
            }
        });
        getContentPane().add(jLabel49);
        jLabel49.setBounds(100, 720, 90, 64);

        jLabel50.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Project\\UI\\Export_64px.png")); // NOI18N
        getContentPane().add(jLabel50);
        jLabel50.setBounds(30, 730, 60, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Project\\UI\\Blurred-Background.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1180, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                try
        {
            // Class.forName("Java.MySQL.Driver");
            String path = "jdbc:mysql://localhost:3305/wildlife";
            String user = "admin";
            String pass = "1234";
            Connection con = DriverManager.getConnection(path,user,pass);
            Connection con3 = DriverManager.getConnection(path,user,pass);
            int Animal_id = Integer.parseInt(jTextField14.getText());
            int employee_id = Integer.parseInt(jLabel2.getText());
            String poachername = jTextField15.getText();
            String query = "SELECT endangered_S FROM animal WHERE animal_id = '"+Animal_id+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            rs.beforeFirst();
            rs.next();
            String getc = rs.getString("endangered_S");
            int i = Integer.parseInt(getc);
            String query3 = "SELECT alive FROM animal WHERE animal_id = '"+Animal_id+"'";
            Statement st3 = con3.createStatement();
            ResultSet rs3 = st3.executeQuery(query3);
            rs3.beforeFirst();
            rs3.next();
            String getc3 = rs3.getString("alive");
            int j = Integer.parseInt(getc3);
            Connection con1 = DriverManager.getConnection(path,user,pass);
            Statement st1 = con1.createStatement();
            if(j==0){
                JOptionPane.showMessageDialog(null, "Animal already dead");
            }
            else
            {
                if(i==0)
                    jLabel45.setText("2000");
            else
                    jLabel45.setText("10000");
                int punish = Integer.parseInt(jLabel45.getText());
                String query1 = "INSERT INTO poacher(fine,aid,eid,name) VALUES('"+punish+"','"+Animal_id+"','"+employee_id+"','"+poachername+"')";
                st1.executeUpdate(query1);
            }
            
            Connection con2 = DriverManager.getConnection(path,user,pass);
            Statement st2 = con2.createStatement();
            String query2 = "UPDATE animal SET alive = '"+0+"' WHERE animal_id = '"+Animal_id+"'";
            st2.executeUpdate(query2);
            //rs1.beforeFirst();
            //rs1.next();

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Error Found" +ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel49MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MousePressed
        // TODO add your handling code here:
        this.hide();
        LoginPass re=new LoginPass();
        re.setVisible(true);
        re.pack();
        re.setLocationRelativeTo(null);
        re.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel49MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PamHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PamHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PamHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PamHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PamHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    // End of variables declaration//GEN-END:variables
}
